#include <unity.h>
void setUp() {}
void tearDown() {}
void test_buffer_starts_empty();
void test_push_increases_size();
void test_pop_returns_pushed_value();
void test_fifo_order();
void test_push_fails_when_full();
void test_pop_fails_when_empty();
void test_peek_returns_value_without_removing();
void test_peek_fails_when_empty();
void test_clear_empties_buffer();
void test_wrap_around();
void test_buffer_fill_empty_cycle();
void test_secure_wipe_zeros_memory();
void test_secure_wipe_zero_length_safe();
void test_secure_wipe_partial();
void test_result_with_value_is_ok();
void test_result_with_error_is_not_ok();
void test_value_or_returns_value_when_ok();
void test_value_or_returns_default_when_error();
void test_status_success_is_ok();
void test_status_with_error();
void test_all_error_codes();
void test_map_preserves_value_when_ok();
void test_map_propagates_error();
void test_map_changes_type();
void test_and_then_continues_when_ok_returns_ok();
void test_and_then_propagates_error_from_fn();
void test_and_then_propagates_initial_error();
void test_status_and_then_continues_when_ok_returns_ok();
void test_status_and_then_propagates_error_from_fn();
void test_status_and_then_propagates_initial_error();
void test_error_code_to_string_none();
void test_error_code_to_string_invalid_parameter();
void test_error_code_to_string_buffer_overflow();
void test_error_code_to_string_timeout();
void test_version_equality();
void test_version_comparison_major();
void test_version_comparison_minor();
void test_version_comparison_patch();
void test_version_comparison_equal();
void test_firmware_version_defined();
void test_radio_config_meshcore_defaults();
void test_radio_init_stores_config();
void test_radio_send_stores_data();
void test_radio_event_handler_receives_tx_done();
void test_radio_event_handler_receives_rx_done();
void test_radio_sleep_called();
void test_radio_standby_called();
void test_radio_start_receive();
void test_lora_bandwidth_enum_values();
void test_radio_send_sets_transmitting();
void test_radio_tx_done_clears_transmitting();
void test_radio_tx_timeout_clears_transmitting();
void test_radio_read_instant_rssi();
void test_storage_init_sets_size();
void test_storage_init_twice_fails();
void test_storage_read_write();
void test_storage_read_uninitialized_fails();
void test_storage_write_uninitialized_fails();
void test_storage_read_out_of_bounds_fails();
void test_storage_write_out_of_bounds_fails();
void test_storage_block_read_write();
void test_storage_commit_called();
void test_storage_deinit();
void test_power_get_source();
void test_power_get_battery_millivolts();
void test_power_get_battery_percent();
void test_power_enter_sleep();
void test_power_wake_up();
void test_power_enable_vext();
void test_board_reset();
void test_board_get_unique_id();
void test_board_get_random_seed();
void test_board_disable_enable_interrupts();
void test_board_feed_watchdog();
void test_crypto_constants_match_meshcore();
void test_dedup_table_sizes_match_meshcore();
void test_ed25519_create_keypair_succeeds();
void test_ed25519_same_seed_produces_same_keys();
void test_ed25519_derive_public_key_matches_create();
void test_ed25519_sign_succeeds();
void test_ed25519_sign_different_messages_different_signatures();
void test_identity_all_zeros_is_invalid();
void test_identity_with_nonzero_private_key_is_valid();
void test_rng_fill_with_preset_data();
void test_rng_fill_wraps_preset_data();
void test_identity_manager_storage_size_correct();
void test_identity_manager_has_identity_false_when_empty();
void test_identity_manager_generate_creates_valid_identity();
void test_identity_manager_generate_uses_rng_for_seed();
void test_identity_manager_save_writes_to_storage();
void test_identity_manager_save_then_load_roundtrip();
void test_identity_manager_load_fails_when_empty();
void test_identity_manager_load_or_create_creates_when_empty();
void test_identity_manager_load_or_create_loads_existing();
void test_identity_manager_load_or_create_regenerates_when_stored_invalid();
void test_identity_manager_has_identity_true_after_save();
void test_identity_manager_logs_key_generation();
void test_identity_storage_format_matches_meshcore();
void test_packet_default_construction();
void test_packet_make_header();
void test_packet_make_header_with_version();
void test_packet_get_route_type_flood();
void test_packet_get_route_type_direct();
void test_packet_get_route_type_transport_flood();
void test_packet_get_route_type_transport_direct();
void test_packet_get_payload_type();
void test_packet_get_payload_type_all_values();
void test_packet_get_payload_version();
void test_packet_has_transport_codes_false();
void test_packet_has_transport_codes_true();
void test_packet_is_flood_route();
void test_packet_is_direct_route();
void test_decode_minimal_packet();
void test_decode_packet_with_path();
void test_decode_packet_with_transport_codes();
void test_decode_packet_direct_route_with_path();
void test_decode_fails_empty_buffer();
void test_decode_fails_buffer_too_small();
void test_decode_fails_path_too_long();
void test_decode_fails_path_exceeds_buffer();
void test_decode_fails_no_payload();
void test_decode_fails_transport_codes_truncated();
void test_decode_clears_transport_codes_when_not_present();
void test_encode_minimal_packet();
void test_encode_packet_with_path();
void test_encode_packet_with_transport_codes();
void test_encode_decode_roundtrip();
void test_encode_decode_roundtrip_with_transport();
void test_packet_get_raw_length_minimal();
void test_packet_get_raw_length_with_path();
void test_packet_get_raw_length_with_transport();
void test_payload_type_name_returns_correct_strings();
void test_route_type_name_returns_correct_strings();
void test_format_packet_stats_minimal();
void test_format_packet_stats_with_path();
void test_format_packet_stats_buffer_safety();
void test_extract_partial_packet_info_from_valid_header();
void test_extract_partial_packet_info_from_decode_error();
void test_extract_partial_packet_info_with_transport_codes();
void test_extract_partial_packet_info_empty_buffer();
void test_extract_partial_packet_info_too_short();
void test_decode_fails_too_many_hops();
void test_decode_succeeds_at_max_hops();
void test_decode_succeeds_under_max_hops();
void test_decode_fails_too_many_hops_with_transport_codes();
void test_encode_fails_null_destination();
void test_encode_fails_path_too_long();
void test_encode_fails_payload_too_long();
void test_remove_self_from_path_empty();
void test_append_snr_to_path_at_max();
void test_time_sync_initial_offset_is_zero();
void test_time_sync_no_samples_means_no_adjustment();
void test_time_sync_single_sample_sets_offset();
void test_time_sync_requires_min_samples_for_consensus();
void test_time_sync_consensus_with_enough_unique_senders();
void test_time_sync_duplicate_sender_not_counted_twice();
void test_time_sync_duplicate_sender_updates_offset();
void test_time_sync_median_offset_used();
void test_time_sync_handles_backward_adjustment();
void test_time_sync_handles_power_loss_scenario();
void test_time_sync_outlier_rejected();
void test_time_sync_max_senders_limit();
void test_time_sync_reset_clears_all();
void test_time_sync_get_adjusted_time_without_consensus_returns_local();
void test_time_sync_adjusted_time_with_consensus();
void test_extract_advert_timestamp_valid();
void test_extract_advert_timestamp_too_short();
void test_extract_advert_timestamp_null_payload();
void test_extract_advert_sender_hash_is_first_pubkey_byte();
void test_time_sync_evicts_oldest_when_full();
void test_time_sync_eviction_updates_oldest_slot();
void test_time_sync_continuous_adjustment();
void test_time_sync_uptime_with_unix_timestamp_jan2026();
void test_time_sync_uptime_detects_year_2094_bug();

void test_packet_history_initial_state_is_empty();
void test_packet_history_has_seen_returns_false_for_new_packet();
void test_packet_history_has_seen_adds_packet_on_first_check();
void test_packet_history_has_seen_returns_true_for_duplicate();
void test_packet_history_tracks_multiple_unique_packets();
void test_packet_history_duplicate_does_not_increase_count();
void test_packet_history_clear_resets_state();

void test_packet_history_ack_uses_payload_directly();
void test_packet_history_ack_stored_separately();
void test_packet_history_ack_different_crcs_not_duplicates();
void test_packet_history_ack_cleared_separately();
void test_packet_history_ack_max_capacity();
void test_packet_history_ack_eviction_is_cyclic();

void test_packet_history_linear_search_finds_all_entries();
void test_packet_history_handles_max_capacity();
void test_packet_history_cyclic_eviction();

void test_packet_history_calculate_hash_from_packet();
void test_packet_history_different_packets_have_different_hashes();
void test_packet_history_hash_ignores_path_for_flood();
void test_packet_hash_only_uses_payload_type_not_full_header();
void test_packet_hash_different_payload_types_differ();
void test_packet_hash_trace_includes_path_len();
void test_packet_hash_non_trace_ignores_path_len();

void test_packet_history_contains_returns_false_for_new_packet();
void test_packet_history_contains_returns_true_after_has_seen();
void test_packet_history_contains_does_not_add_to_history();
void test_packet_history_contains_works_for_ack();

void test_packet_history_clear_removes_specific_packet();

void test_packet_history_tracks_duplicate_stats();
void test_packet_history_tracks_direct_duplicate_stats();
void test_packet_history_reset_stats();

void test_edge_same_packet_detected_on_every_check();
void test_edge_same_packet_different_route_type_is_duplicate();
void test_edge_same_packet_with_different_path_is_duplicate();
void test_edge_same_packet_with_different_snr_is_duplicate();
void test_edge_same_packet_with_transport_codes_is_duplicate();
void test_edge_single_byte_difference_not_duplicate();
void test_edge_different_payload_length_not_duplicate();
void test_edge_different_payload_type_not_duplicate();
void test_edge_ack_same_crc_always_duplicate();
void test_edge_ack_different_route_is_duplicate();
void test_edge_ack_with_extra_payload_bytes_still_uses_first_4();
void test_edge_ack_vs_non_ack_same_payload_not_duplicate();
void test_edge_trace_different_path_len_not_duplicate();
void test_edge_trace_same_path_len_is_duplicate();
void test_edge_packet_at_capacity_boundary_still_found();
void test_edge_first_packet_evicted_after_overflow();
void test_edge_recently_evicted_packet_detected_as_new();
void test_edge_ack_capacity_boundary();
void test_edge_linear_search_finds_any_position();
void test_edge_all_same_first_hash_byte_still_unique();
void test_edge_rapid_duplicate_burst();
void test_edge_interleaved_packets_all_tracked();
void test_edge_zero_length_payload_tracked();
void test_edge_single_byte_payload_tracked();
void test_edge_all_zeros_payload_tracked();
void test_edge_all_ones_payload_tracked();
void test_edge_max_size_payload_tracked();
void test_edge_multipart_ack_detected_as_duplicate();
void test_edge_all_payload_types_tracked();
void test_edge_contains_never_adds_packet();
void test_edge_contains_ack_never_adds();
void test_repeater_config_default_values();
void test_repeater_slot_airtime_is_300ms();
void test_repeater_disabled_returns_no_action();
void test_repeater_direct_route_not_next_hop_returns_drop();
void test_repeater_flood_route_returns_forward();
void test_repeater_transport_flood_returns_forward();
void test_repeater_path_at_max_returns_drop();
void test_repeater_path_exceeds_max_returns_drop();
void test_repeater_duplicate_packet_returns_drop();
void test_repeater_marks_packet_as_seen();
void test_repeater_append_self_hash_increments_path();
void test_repeater_append_self_hash_fails_at_max_path();
void test_repeater_calculate_delay_returns_randomized_value();
void test_repeater_calculate_delay_trace_returns_zero();
void test_repeater_calculate_delay_direct_non_trace_has_delay();
void test_repeater_get_priority_based_on_payload_type();
void test_repeater_direct_route_we_are_next_hop_returns_forward();
void test_repeater_direct_route_empty_path_returns_drop();
void test_repeater_remove_self_from_path_shifts_path();
void test_repeater_remove_self_from_path_single_element();
void test_repeater_transport_direct_we_are_next_hop_returns_forward();
void test_repeater_direct_route_duplicate_returns_drop();
void test_repeater_direct_priority_is_highest();
void test_repeater_trace_we_are_next_hop_returns_forward();
void test_repeater_trace_not_next_hop_returns_drop();
void test_repeater_trace_second_hop_check();
void test_repeater_trace_reached_end_returns_drop();
void test_repeater_trace_append_snr_not_hash();
void test_repeater_is_trace_packet();
void test_repeater_advert_priority_is_lowest();
void test_repeater_control_packet_zero_hop_returns_drop();
void test_repeater_control_packet_with_path_returns_drop();
void test_repeater_direct_packet_final_destination_unsupported_drops();
void test_repeater_direct_packet_final_destination_control_drops();
void test_repeater_direct_packet_not_final_destination_forwards();
void test_repeater_control_packet_flood_route_returns_drop();
void test_repeater_is_control_packet();
void test_is_valid_control_request_direct_zero_hop_with_flag();
void test_is_valid_control_request_fails_flood_route();
void test_is_valid_control_request_fails_non_zero_path();
void test_is_valid_control_request_fails_missing_flag();
void test_is_valid_control_request_fails_empty_payload();
void test_is_valid_control_request_fails_non_control_type();
void test_repeater_flood_packet_with_self_in_path_still_forwards();
void test_repeater_flood_packet_final_destination_control_drops();
void test_repeater_flood_packet_not_final_destination_forwards();
void test_repeater_trace_2byte_hash_we_are_next_hop();
void test_repeater_trace_2byte_hash_partial_match_drops();
void test_repeater_trace_4byte_hash_we_are_next_hop();
void test_repeater_raw_custom_flood_returns_drop();
void test_repeater_raw_custom_transport_flood_returns_drop();
void test_repeater_raw_custom_direct_we_are_next_hop_forwards();
void test_repeater_flood_with_self_hash_in_path_still_forwards_if_not_seen();
void test_repeater_flood_anon_request_destined_for_self_drops();
void test_repeater_flood_anon_request_destined_for_other_forwards();
void test_repeater_flood_request_destined_for_self_drops();
void test_repeater_flood_response_destined_for_self_drops();
void test_repeater_flood_text_message_destined_for_self_drops();
void test_repeater_flood_path_destined_for_self_drops();
void test_repeater_flood_advert_no_dest_hash_forwards();
void test_repeater_flood_ack_no_dest_hash_forwards();
void test_repeater_config_drop_repeater_adverts_default_false();
void test_repeater_drop_repeater_adverts_disabled_forwards_all();
void test_repeater_drop_repeater_adverts_enabled_drops_repeater_advert();
void test_repeater_drop_repeater_adverts_enabled_forwards_companion_advert();
void test_repeater_drop_repeater_adverts_enabled_drops_room_advert();
void test_repeater_drop_repeater_adverts_enabled_still_forwards_text();
void test_repeater_drop_repeater_adverts_short_payload_forwards();
void test_parse_discover_request_valid();
void test_parse_discover_request_prefix_only();
void test_parse_discover_request_too_short();
void test_parse_discover_request_wrong_type();
void test_parse_discover_request_null_payload();
void test_matches_node_type_repeater();
void test_matches_node_type_no_match();
void test_create_discover_response_full_key();
void test_create_discover_response_prefix_only();
void test_create_discover_response_null_buffer();
void test_encode_advert_data_type_only();
void test_encode_advert_data_with_name();
void test_encode_advert_data_name_truncated();
void test_encode_advert_data_null_name_no_flag();
void test_encode_advert_data_empty_name_no_flag();
void test_create_advert_packet_structure();
void test_create_advert_packet_has_signature();
void test_create_advert_packet_payload_length();
void test_advert_scheduler_not_due_before_time_sync();
void test_advert_scheduler_not_due_if_recently_sent();
void test_advert_scheduler_due_after_interval();
void test_advert_scheduler_due_if_never_sent();
void test_advert_scheduler_mark_sent_updates_time();
void test_advert_scheduler_persist_and_restore();
void test_advert_scheduler_empty_storage_returns_zero();
void test_advert_scheduler_not_due_if_time_moved_backwards();
void test_tx_queue_initial_state_is_empty();
void test_tx_queue_enqueue_single_packet();
void test_tx_queue_enqueue_rejects_null_data_when_length_nonzero();
void test_tx_queue_enqueue_multiple_packets();
void test_tx_queue_get_next_returns_null_when_empty();
void test_tx_queue_get_next_returns_null_when_not_ready();
void test_tx_queue_get_next_returns_ready_packet();
void test_tx_queue_release_removes_entry();
void test_tx_queue_priority_ordering_lower_first();
void test_tx_queue_time_ordering_when_same_priority();
void test_tx_queue_respects_scheduled_time();
void test_tx_queue_full_returns_false_on_enqueue();
void test_tx_queue_clear_empties_queue();
void test_tx_queue_handles_timestamp_wraparound();
void test_tx_queue_packet_too_large_rejected();
void test_tx_queue_enqueue_packet_encodes_and_stores();
void test_tx_queue_enqueue_packet_stores_correct_encoded_data();
void test_tx_queue_enqueue_packet_respects_scheduled_time();
void test_tx_queue_enqueue_packet_returns_false_when_full();
void test_tx_queue_enqueue_packet_handles_empty_payload();
void test_tx_queue_enqueue_packet_with_transport_codes();
void test_tx_queue_trace_packet_enqueues_normally();
void test_tx_queue_all_packets_use_carrier_sense();
void test_radio_controller_initial_state_is_idle();
void test_radio_controller_transmits_immediately_when_cs_clear();
void test_radio_controller_completes_after_tx_done();
void test_radio_controller_schedules_retry_on_carrier_detected();
void test_radio_controller_retries_cs_after_delay();
void test_radio_controller_transmits_on_retry_success();
void test_radio_controller_transmits_after_max_retries();
void test_radio_controller_rejects_transmit_when_busy();
void test_radio_controller_handles_tx_timeout();
void test_radio_controller_rejects_oversized_data();
void test_radio_controller_uses_custom_cs_config();
void test_cs_config_defaults();
void test_radio_controller_does_not_affect_rx_during_idle();
void test_radio_controller_uses_source_pointer_directly();
void test_radio_controller_data_valid_through_retries();
void test_radio_controller_reports_pending_data_size();
void test_radio_controller_carrier_sense_disabled_by_default();
void test_radio_controller_enable_carrier_sense();
void test_radio_controller_carrier_sense_samples_noise_floor();
void test_radio_controller_carrier_sense_detects_signal_above_threshold();
void test_radio_controller_carrier_sense_ignores_noise();
void test_radio_controller_carrier_sense_schedules_retry_on_carrier();
void test_radio_controller_carrier_sense_transmits_when_clear();
void test_radio_controller_carrier_sense_disabled_transmits_immediately();
void test_radio_controller_carrier_sense_invalid_noise_floor_transmits();
void test_radio_controller_carrier_sense_retry_rechecks_rssi();
void test_radio_controller_configure_carrier_sense_for_bandwidth();
void test_radio_controller_narrow_bandwidth_uses_smaller_margin();
void test_power_save_initial_state_is_active();
void test_power_save_initial_last_repeat_is_zero();
void test_power_save_on_packet_repeated_updates_time();
void test_power_save_multiple_repeats_update_time();
void test_power_save_stays_active_before_timeout();
void test_power_save_enters_sleep_after_timeout();
void test_power_save_sleep_disables_rx();
void test_power_save_enters_sleep_with_no_repeats_from_start();
void test_power_save_wakes_after_sleep_duration();
void test_power_save_wake_enables_rx();
void test_power_save_stays_sleeping_before_duration();
void test_power_save_repeat_resets_timeout();
void test_power_save_wake_resets_last_repeat_time();
void test_power_save_full_cycle_sleep_wake_sleep();
void test_power_save_repeat_during_active_prevents_sleep();
void test_power_save_enabled_disabled();
void test_power_save_is_sleeping_helper();
void test_power_save_custom_config();
void test_power_save_config_defaults();
void test_packet_router_initial_state();
void test_packet_router_set_self_hash();
void test_packet_router_processes_advert_packet();
void test_packet_router_forwards_flood_packet();
void test_packet_router_does_not_forward_duplicate();
void test_packet_router_appends_self_hash_for_flood();
void test_packet_router_does_not_forward_when_disabled();
void test_packet_router_forwards_direct_when_next_hop();
void test_packet_router_drops_direct_when_not_next_hop();
void test_packet_router_does_not_forward_control_packets();
void test_packet_router_calculates_correct_priority();
void test_packet_router_duplicate_flood_never_forwarded_twice();
void test_packet_router_duplicate_control_request_never_triggers_twice();
void test_packet_router_duplicate_advert_still_processes_for_time_sync();
void test_packet_router_different_packets_both_forwarded();
void test_packet_router_control_response_marked_seen_but_not_processed();
void test_packet_router_null_event_handler_no_crash();
void test_packet_router_packet_exceeds_path_limit_not_forwarded();
void test_packet_router_repeater_disabled_no_forward();
void test_packet_router_malformed_discover_request_still_deduped();
void test_packet_router_flood_destined_for_self_not_forwarded();
void test_packet_router_stress_many_unique_packets();
void test_packet_router_stress_same_packet_many_times();
void test_noise_floor_estimator_initial_state_is_invalid();
void test_noise_floor_estimator_becomes_valid_after_min_samples();
void test_noise_floor_estimator_converges_to_stable_value();
void test_noise_floor_estimator_ewma_smooths_values();
void test_noise_floor_estimator_adapts_to_changing_environment();
void test_noise_floor_estimator_threshold_above_noise_floor();
void test_noise_floor_estimator_threshold_based_on_variance();
void test_noise_floor_estimator_minimum_margin_applied();
void test_noise_floor_estimator_detects_signal_above_threshold();
void test_noise_floor_estimator_ignores_signal_below_threshold();
void test_noise_floor_estimator_invalid_always_returns_false();
void test_noise_floor_estimator_respects_custom_min_samples();
void test_noise_floor_estimator_respects_custom_alpha();
void test_noise_floor_estimator_default_config();
void test_noise_floor_estimator_reset_clears_state();
void test_noise_floor_estimator_handles_extreme_rssi_values();
void test_noise_floor_estimator_sample_count_increments();
void test_margin_for_bandwidth_narrow_returns_small_margin();
void test_margin_for_bandwidth_medium_returns_default_margin();
void test_margin_for_bandwidth_wide_returns_larger_margin();
void test_noise_floor_config_for_bandwidth();
void test_noise_floor_estimator_with_bandwidth_config();

void test_path_hash_mode_default_is_max();
void test_path_hash_mode_get_returns_stored_value();
void test_path_hash_mode_set_accepts_0_1_2();
void test_path_hash_mode_set_rejects_3();
void test_path_hash_mode_set_rejects_larger_values();
void test_path_hash_mode_load_from_storage();
void test_path_hash_mode_load_constrains_invalid_stored_value();
void test_path_hash_mode_load_empty_storage_uses_default();
void test_path_hash_mode_save_persists_value();
void test_path_hash_mode_save_then_load_roundtrip();

int main() {
    UNITY_BEGIN();

    RUN_TEST(test_buffer_starts_empty);
    RUN_TEST(test_push_increases_size);
    RUN_TEST(test_pop_returns_pushed_value);
    RUN_TEST(test_fifo_order);
    RUN_TEST(test_push_fails_when_full);
    RUN_TEST(test_pop_fails_when_empty);
    RUN_TEST(test_peek_returns_value_without_removing);
    RUN_TEST(test_peek_fails_when_empty);
    RUN_TEST(test_clear_empties_buffer);
    RUN_TEST(test_wrap_around);
    RUN_TEST(test_buffer_fill_empty_cycle);
    RUN_TEST(test_secure_wipe_zeros_memory);
    RUN_TEST(test_secure_wipe_zero_length_safe);
    RUN_TEST(test_secure_wipe_partial);

    RUN_TEST(test_result_with_value_is_ok);
    RUN_TEST(test_result_with_error_is_not_ok);
    RUN_TEST(test_value_or_returns_value_when_ok);
    RUN_TEST(test_value_or_returns_default_when_error);
    RUN_TEST(test_status_success_is_ok);
    RUN_TEST(test_status_with_error);
    RUN_TEST(test_all_error_codes);
    RUN_TEST(test_map_preserves_value_when_ok);
    RUN_TEST(test_map_propagates_error);
    RUN_TEST(test_map_changes_type);
    RUN_TEST(test_and_then_continues_when_ok_returns_ok);
    RUN_TEST(test_and_then_propagates_error_from_fn);
    RUN_TEST(test_and_then_propagates_initial_error);
    RUN_TEST(test_status_and_then_continues_when_ok_returns_ok);
    RUN_TEST(test_status_and_then_propagates_error_from_fn);
    RUN_TEST(test_status_and_then_propagates_initial_error);
    RUN_TEST(test_error_code_to_string_none);
    RUN_TEST(test_error_code_to_string_invalid_parameter);
    RUN_TEST(test_error_code_to_string_buffer_overflow);
    RUN_TEST(test_error_code_to_string_timeout);

    RUN_TEST(test_version_equality);
    RUN_TEST(test_version_comparison_major);
    RUN_TEST(test_version_comparison_minor);
    RUN_TEST(test_version_comparison_patch);
    RUN_TEST(test_version_comparison_equal);
    RUN_TEST(test_firmware_version_defined);

    RUN_TEST(test_radio_config_meshcore_defaults);
    RUN_TEST(test_radio_init_stores_config);
    RUN_TEST(test_radio_send_stores_data);
    RUN_TEST(test_radio_event_handler_receives_tx_done);
    RUN_TEST(test_radio_event_handler_receives_rx_done);
    RUN_TEST(test_radio_sleep_called);
    RUN_TEST(test_radio_standby_called);
    RUN_TEST(test_radio_start_receive);
    RUN_TEST(test_lora_bandwidth_enum_values);
    RUN_TEST(test_radio_send_sets_transmitting);
    RUN_TEST(test_radio_tx_done_clears_transmitting);
    RUN_TEST(test_radio_tx_timeout_clears_transmitting);
    RUN_TEST(test_radio_read_instant_rssi);

    RUN_TEST(test_storage_init_sets_size);
    RUN_TEST(test_storage_init_twice_fails);
    RUN_TEST(test_storage_read_write);
    RUN_TEST(test_storage_read_uninitialized_fails);
    RUN_TEST(test_storage_write_uninitialized_fails);
    RUN_TEST(test_storage_read_out_of_bounds_fails);
    RUN_TEST(test_storage_write_out_of_bounds_fails);
    RUN_TEST(test_storage_block_read_write);
    RUN_TEST(test_storage_commit_called);
    RUN_TEST(test_storage_deinit);

    RUN_TEST(test_power_get_source);
    RUN_TEST(test_power_get_battery_millivolts);
    RUN_TEST(test_power_get_battery_percent);
    RUN_TEST(test_power_enter_sleep);
    RUN_TEST(test_power_wake_up);
    RUN_TEST(test_power_enable_vext);

    RUN_TEST(test_board_reset);
    RUN_TEST(test_board_get_unique_id);
    RUN_TEST(test_board_get_random_seed);
    RUN_TEST(test_board_disable_enable_interrupts);
    RUN_TEST(test_board_feed_watchdog);

    RUN_TEST(test_crypto_constants_match_meshcore);
    RUN_TEST(test_dedup_table_sizes_match_meshcore);
    RUN_TEST(test_ed25519_create_keypair_succeeds);
    RUN_TEST(test_ed25519_same_seed_produces_same_keys);
    RUN_TEST(test_ed25519_derive_public_key_matches_create);
    RUN_TEST(test_ed25519_sign_succeeds);
    RUN_TEST(test_ed25519_sign_different_messages_different_signatures);
    RUN_TEST(test_identity_all_zeros_is_invalid);
    RUN_TEST(test_identity_with_nonzero_private_key_is_valid);
    RUN_TEST(test_rng_fill_with_preset_data);
    RUN_TEST(test_rng_fill_wraps_preset_data);
    RUN_TEST(test_identity_manager_storage_size_correct);
    RUN_TEST(test_identity_manager_has_identity_false_when_empty);
    RUN_TEST(test_identity_manager_generate_creates_valid_identity);
    RUN_TEST(test_identity_manager_generate_uses_rng_for_seed);
    RUN_TEST(test_identity_manager_save_writes_to_storage);
    RUN_TEST(test_identity_manager_save_then_load_roundtrip);
    RUN_TEST(test_identity_manager_load_fails_when_empty);
    RUN_TEST(test_identity_manager_load_or_create_creates_when_empty);
    RUN_TEST(test_identity_manager_load_or_create_loads_existing);
    RUN_TEST(test_identity_manager_load_or_create_regenerates_when_stored_invalid);
    RUN_TEST(test_identity_manager_has_identity_true_after_save);
    RUN_TEST(test_identity_manager_logs_key_generation);
    RUN_TEST(test_identity_storage_format_matches_meshcore);

    RUN_TEST(test_packet_default_construction);
    RUN_TEST(test_packet_make_header);
    RUN_TEST(test_packet_make_header_with_version);
    RUN_TEST(test_packet_get_route_type_flood);
    RUN_TEST(test_packet_get_route_type_direct);
    RUN_TEST(test_packet_get_route_type_transport_flood);
    RUN_TEST(test_packet_get_route_type_transport_direct);
    RUN_TEST(test_packet_get_payload_type);
    RUN_TEST(test_packet_get_payload_type_all_values);
    RUN_TEST(test_packet_get_payload_version);
    RUN_TEST(test_packet_has_transport_codes_false);
    RUN_TEST(test_packet_has_transport_codes_true);
    RUN_TEST(test_packet_is_flood_route);
    RUN_TEST(test_packet_is_direct_route);
    RUN_TEST(test_decode_minimal_packet);
    RUN_TEST(test_decode_packet_with_path);
    RUN_TEST(test_decode_packet_with_transport_codes);
    RUN_TEST(test_decode_packet_direct_route_with_path);
    RUN_TEST(test_decode_fails_empty_buffer);
    RUN_TEST(test_decode_fails_buffer_too_small);
    RUN_TEST(test_decode_fails_path_too_long);
    RUN_TEST(test_decode_fails_path_exceeds_buffer);
    RUN_TEST(test_decode_fails_no_payload);
    RUN_TEST(test_decode_fails_transport_codes_truncated);
    RUN_TEST(test_decode_clears_transport_codes_when_not_present);
    RUN_TEST(test_encode_minimal_packet);
    RUN_TEST(test_encode_packet_with_path);
    RUN_TEST(test_encode_packet_with_transport_codes);
    RUN_TEST(test_encode_decode_roundtrip);
    RUN_TEST(test_encode_decode_roundtrip_with_transport);
    RUN_TEST(test_packet_get_raw_length_minimal);
    RUN_TEST(test_packet_get_raw_length_with_path);
    RUN_TEST(test_packet_get_raw_length_with_transport);
    RUN_TEST(test_payload_type_name_returns_correct_strings);
    RUN_TEST(test_route_type_name_returns_correct_strings);
    RUN_TEST(test_format_packet_stats_minimal);
    RUN_TEST(test_format_packet_stats_with_path);
    RUN_TEST(test_format_packet_stats_buffer_safety);

    RUN_TEST(test_extract_partial_packet_info_from_valid_header);
    RUN_TEST(test_extract_partial_packet_info_from_decode_error);
    RUN_TEST(test_extract_partial_packet_info_with_transport_codes);
    RUN_TEST(test_extract_partial_packet_info_empty_buffer);
    RUN_TEST(test_extract_partial_packet_info_too_short);
    RUN_TEST(test_decode_fails_too_many_hops);
    RUN_TEST(test_decode_succeeds_at_max_hops);
    RUN_TEST(test_decode_succeeds_under_max_hops);
    RUN_TEST(test_decode_fails_too_many_hops_with_transport_codes);
    RUN_TEST(test_encode_fails_null_destination);
    RUN_TEST(test_encode_fails_path_too_long);
    RUN_TEST(test_encode_fails_payload_too_long);
    RUN_TEST(test_remove_self_from_path_empty);
    RUN_TEST(test_append_snr_to_path_at_max);
        RUN_TEST(test_time_sync_initial_offset_is_zero);
    RUN_TEST(test_time_sync_no_samples_means_no_adjustment);
    RUN_TEST(test_time_sync_single_sample_sets_offset);
    RUN_TEST(test_time_sync_requires_min_samples_for_consensus);
    RUN_TEST(test_time_sync_consensus_with_enough_unique_senders);
    RUN_TEST(test_time_sync_duplicate_sender_not_counted_twice);
    RUN_TEST(test_time_sync_duplicate_sender_updates_offset);
    RUN_TEST(test_time_sync_median_offset_used);
    RUN_TEST(test_time_sync_handles_backward_adjustment);
    RUN_TEST(test_time_sync_handles_power_loss_scenario);
    RUN_TEST(test_time_sync_outlier_rejected);
    RUN_TEST(test_time_sync_max_senders_limit);
    RUN_TEST(test_time_sync_reset_clears_all);
    RUN_TEST(test_time_sync_get_adjusted_time_without_consensus_returns_local);
    RUN_TEST(test_time_sync_adjusted_time_with_consensus);
    RUN_TEST(test_extract_advert_timestamp_valid);
    RUN_TEST(test_extract_advert_timestamp_too_short);
    RUN_TEST(test_extract_advert_timestamp_null_payload);
    RUN_TEST(test_extract_advert_sender_hash_is_first_pubkey_byte);
    RUN_TEST(test_time_sync_evicts_oldest_when_full);
    RUN_TEST(test_time_sync_eviction_updates_oldest_slot);
    RUN_TEST(test_time_sync_continuous_adjustment);
    RUN_TEST(test_time_sync_uptime_with_unix_timestamp_jan2026);
    RUN_TEST(test_time_sync_uptime_detects_year_2094_bug);

    RUN_TEST(test_packet_history_initial_state_is_empty);
    RUN_TEST(test_packet_history_has_seen_returns_false_for_new_packet);
    RUN_TEST(test_packet_history_has_seen_adds_packet_on_first_check);
    RUN_TEST(test_packet_history_has_seen_returns_true_for_duplicate);
    RUN_TEST(test_packet_history_tracks_multiple_unique_packets);
    RUN_TEST(test_packet_history_duplicate_does_not_increase_count);
    RUN_TEST(test_packet_history_clear_resets_state);

    RUN_TEST(test_packet_history_ack_uses_payload_directly);
    RUN_TEST(test_packet_history_ack_stored_separately);
    RUN_TEST(test_packet_history_ack_different_crcs_not_duplicates);
    RUN_TEST(test_packet_history_ack_cleared_separately);
    RUN_TEST(test_packet_history_ack_max_capacity);
    RUN_TEST(test_packet_history_ack_eviction_is_cyclic);

    RUN_TEST(test_packet_history_linear_search_finds_all_entries);
    RUN_TEST(test_packet_history_handles_max_capacity);
    RUN_TEST(test_packet_history_cyclic_eviction);

    RUN_TEST(test_packet_history_calculate_hash_from_packet);
    RUN_TEST(test_packet_history_different_packets_have_different_hashes);
    RUN_TEST(test_packet_history_hash_ignores_path_for_flood);
    RUN_TEST(test_packet_hash_only_uses_payload_type_not_full_header);
    RUN_TEST(test_packet_hash_different_payload_types_differ);
    RUN_TEST(test_packet_hash_trace_includes_path_len);
    RUN_TEST(test_packet_hash_non_trace_ignores_path_len);

    RUN_TEST(test_packet_history_contains_returns_false_for_new_packet);
    RUN_TEST(test_packet_history_contains_returns_true_after_has_seen);
    RUN_TEST(test_packet_history_contains_does_not_add_to_history);
    RUN_TEST(test_packet_history_contains_works_for_ack);

    RUN_TEST(test_packet_history_clear_removes_specific_packet);

    RUN_TEST(test_packet_history_tracks_duplicate_stats);
    RUN_TEST(test_packet_history_tracks_direct_duplicate_stats);
    RUN_TEST(test_packet_history_reset_stats);

    RUN_TEST(test_edge_same_packet_detected_on_every_check);
    RUN_TEST(test_edge_same_packet_different_route_type_is_duplicate);
    RUN_TEST(test_edge_same_packet_with_different_path_is_duplicate);
    RUN_TEST(test_edge_same_packet_with_different_snr_is_duplicate);
    RUN_TEST(test_edge_same_packet_with_transport_codes_is_duplicate);
    RUN_TEST(test_edge_single_byte_difference_not_duplicate);
    RUN_TEST(test_edge_different_payload_length_not_duplicate);
    RUN_TEST(test_edge_different_payload_type_not_duplicate);
    RUN_TEST(test_edge_ack_same_crc_always_duplicate);
    RUN_TEST(test_edge_ack_different_route_is_duplicate);
    RUN_TEST(test_edge_ack_with_extra_payload_bytes_still_uses_first_4);
    RUN_TEST(test_edge_ack_vs_non_ack_same_payload_not_duplicate);
    RUN_TEST(test_edge_trace_different_path_len_not_duplicate);
    RUN_TEST(test_edge_trace_same_path_len_is_duplicate);
    RUN_TEST(test_edge_packet_at_capacity_boundary_still_found);
    RUN_TEST(test_edge_first_packet_evicted_after_overflow);
    RUN_TEST(test_edge_recently_evicted_packet_detected_as_new);
    RUN_TEST(test_edge_ack_capacity_boundary);
    RUN_TEST(test_edge_linear_search_finds_any_position);
    RUN_TEST(test_edge_all_same_first_hash_byte_still_unique);
    RUN_TEST(test_edge_rapid_duplicate_burst);
    RUN_TEST(test_edge_interleaved_packets_all_tracked);
    RUN_TEST(test_edge_zero_length_payload_tracked);
    RUN_TEST(test_edge_single_byte_payload_tracked);
    RUN_TEST(test_edge_all_zeros_payload_tracked);
    RUN_TEST(test_edge_all_ones_payload_tracked);
    RUN_TEST(test_edge_max_size_payload_tracked);
    RUN_TEST(test_edge_multipart_ack_detected_as_duplicate);
    RUN_TEST(test_edge_all_payload_types_tracked);
    RUN_TEST(test_edge_contains_never_adds_packet);
    RUN_TEST(test_edge_contains_ack_never_adds);
        RUN_TEST(test_repeater_config_default_values);
    RUN_TEST(test_repeater_slot_airtime_is_300ms);
    RUN_TEST(test_repeater_disabled_returns_no_action);
    RUN_TEST(test_repeater_direct_route_not_next_hop_returns_drop);
    RUN_TEST(test_repeater_flood_route_returns_forward);
    RUN_TEST(test_repeater_transport_flood_returns_forward);
    RUN_TEST(test_repeater_path_at_max_returns_drop);
    RUN_TEST(test_repeater_path_exceeds_max_returns_drop);
    RUN_TEST(test_repeater_duplicate_packet_returns_drop);
    RUN_TEST(test_repeater_marks_packet_as_seen);
    RUN_TEST(test_repeater_append_self_hash_increments_path);
    RUN_TEST(test_repeater_append_self_hash_fails_at_max_path);
    RUN_TEST(test_repeater_calculate_delay_returns_randomized_value);
    RUN_TEST(test_repeater_calculate_delay_trace_returns_zero);
    RUN_TEST(test_repeater_calculate_delay_direct_non_trace_has_delay);
    RUN_TEST(test_repeater_get_priority_based_on_payload_type);
    RUN_TEST(test_repeater_direct_route_we_are_next_hop_returns_forward);
    RUN_TEST(test_repeater_direct_route_empty_path_returns_drop);
    RUN_TEST(test_repeater_remove_self_from_path_shifts_path);
    RUN_TEST(test_repeater_remove_self_from_path_single_element);
    RUN_TEST(test_repeater_transport_direct_we_are_next_hop_returns_forward);
    RUN_TEST(test_repeater_direct_route_duplicate_returns_drop);
    RUN_TEST(test_repeater_direct_priority_is_highest);
    RUN_TEST(test_repeater_trace_we_are_next_hop_returns_forward);
    RUN_TEST(test_repeater_trace_not_next_hop_returns_drop);
    RUN_TEST(test_repeater_trace_second_hop_check);
    RUN_TEST(test_repeater_trace_reached_end_returns_drop);
    RUN_TEST(test_repeater_trace_append_snr_not_hash);
    RUN_TEST(test_repeater_is_trace_packet);
    RUN_TEST(test_repeater_advert_priority_is_lowest);
    RUN_TEST(test_repeater_control_packet_zero_hop_returns_drop);
    RUN_TEST(test_repeater_control_packet_with_path_returns_drop);
    RUN_TEST(test_repeater_direct_packet_final_destination_unsupported_drops);
    RUN_TEST(test_repeater_direct_packet_final_destination_control_drops);
    RUN_TEST(test_repeater_direct_packet_not_final_destination_forwards);
    RUN_TEST(test_repeater_control_packet_flood_route_returns_drop);
    RUN_TEST(test_repeater_is_control_packet);
    RUN_TEST(test_is_valid_control_request_direct_zero_hop_with_flag);
    RUN_TEST(test_is_valid_control_request_fails_flood_route);
    RUN_TEST(test_is_valid_control_request_fails_non_zero_path);
    RUN_TEST(test_is_valid_control_request_fails_missing_flag);
    RUN_TEST(test_is_valid_control_request_fails_empty_payload);
    RUN_TEST(test_is_valid_control_request_fails_non_control_type);
    RUN_TEST(test_repeater_flood_packet_with_self_in_path_still_forwards);
    RUN_TEST(test_repeater_flood_packet_final_destination_control_drops);
    RUN_TEST(test_repeater_flood_packet_not_final_destination_forwards);
    RUN_TEST(test_repeater_trace_2byte_hash_we_are_next_hop);
    RUN_TEST(test_repeater_trace_2byte_hash_partial_match_drops);
    RUN_TEST(test_repeater_trace_4byte_hash_we_are_next_hop);
    RUN_TEST(test_repeater_raw_custom_flood_returns_drop);
    RUN_TEST(test_repeater_raw_custom_transport_flood_returns_drop);
    RUN_TEST(test_repeater_raw_custom_direct_we_are_next_hop_forwards);
    RUN_TEST(test_repeater_flood_with_self_hash_in_path_still_forwards_if_not_seen);
    RUN_TEST(test_repeater_flood_anon_request_destined_for_self_drops);
    RUN_TEST(test_repeater_flood_anon_request_destined_for_other_forwards);
    RUN_TEST(test_repeater_flood_request_destined_for_self_drops);
    RUN_TEST(test_repeater_flood_response_destined_for_self_drops);
    RUN_TEST(test_repeater_flood_text_message_destined_for_self_drops);
    RUN_TEST(test_repeater_flood_path_destined_for_self_drops);
    RUN_TEST(test_repeater_flood_advert_no_dest_hash_forwards);
    RUN_TEST(test_repeater_flood_ack_no_dest_hash_forwards);
    RUN_TEST(test_repeater_config_drop_repeater_adverts_default_false);
    RUN_TEST(test_repeater_drop_repeater_adverts_disabled_forwards_all);
    RUN_TEST(test_repeater_drop_repeater_adverts_enabled_drops_repeater_advert);
    RUN_TEST(test_repeater_drop_repeater_adverts_enabled_forwards_companion_advert);
    RUN_TEST(test_repeater_drop_repeater_adverts_enabled_drops_room_advert);
    RUN_TEST(test_repeater_drop_repeater_adverts_enabled_still_forwards_text);
    RUN_TEST(test_repeater_drop_repeater_adverts_short_payload_forwards);
        RUN_TEST(test_parse_discover_request_valid);
    RUN_TEST(test_parse_discover_request_prefix_only);
    RUN_TEST(test_parse_discover_request_too_short);
    RUN_TEST(test_parse_discover_request_wrong_type);
    RUN_TEST(test_parse_discover_request_null_payload);
    RUN_TEST(test_matches_node_type_repeater);
    RUN_TEST(test_matches_node_type_no_match);
    RUN_TEST(test_create_discover_response_full_key);
    RUN_TEST(test_create_discover_response_prefix_only);
    RUN_TEST(test_create_discover_response_null_buffer);
        RUN_TEST(test_encode_advert_data_type_only);
    RUN_TEST(test_encode_advert_data_with_name);
    RUN_TEST(test_encode_advert_data_name_truncated);
    RUN_TEST(test_encode_advert_data_null_name_no_flag);
    RUN_TEST(test_encode_advert_data_empty_name_no_flag);
    RUN_TEST(test_create_advert_packet_structure);
    RUN_TEST(test_create_advert_packet_has_signature);
    RUN_TEST(test_create_advert_packet_payload_length);
    RUN_TEST(test_advert_scheduler_not_due_before_time_sync);
    RUN_TEST(test_advert_scheduler_not_due_if_recently_sent);
    RUN_TEST(test_advert_scheduler_due_after_interval);
    RUN_TEST(test_advert_scheduler_due_if_never_sent);
    RUN_TEST(test_advert_scheduler_mark_sent_updates_time);
    RUN_TEST(test_advert_scheduler_persist_and_restore);
    RUN_TEST(test_advert_scheduler_empty_storage_returns_zero);
    RUN_TEST(test_advert_scheduler_not_due_if_time_moved_backwards);
        RUN_TEST(test_tx_queue_initial_state_is_empty);
    RUN_TEST(test_tx_queue_enqueue_single_packet);
    RUN_TEST(test_tx_queue_enqueue_rejects_null_data_when_length_nonzero);
    RUN_TEST(test_tx_queue_enqueue_multiple_packets);
    RUN_TEST(test_tx_queue_get_next_returns_null_when_empty);
    RUN_TEST(test_tx_queue_get_next_returns_null_when_not_ready);
    RUN_TEST(test_tx_queue_get_next_returns_ready_packet);
    RUN_TEST(test_tx_queue_release_removes_entry);
    RUN_TEST(test_tx_queue_priority_ordering_lower_first);
    RUN_TEST(test_tx_queue_time_ordering_when_same_priority);
    RUN_TEST(test_tx_queue_respects_scheduled_time);
    RUN_TEST(test_tx_queue_full_returns_false_on_enqueue);
    RUN_TEST(test_tx_queue_clear_empties_queue);
    RUN_TEST(test_tx_queue_handles_timestamp_wraparound);
    RUN_TEST(test_tx_queue_packet_too_large_rejected);
    RUN_TEST(test_tx_queue_enqueue_packet_encodes_and_stores);
    RUN_TEST(test_tx_queue_enqueue_packet_stores_correct_encoded_data);
    RUN_TEST(test_tx_queue_enqueue_packet_respects_scheduled_time);
    RUN_TEST(test_tx_queue_enqueue_packet_returns_false_when_full);
    RUN_TEST(test_tx_queue_enqueue_packet_handles_empty_payload);
    RUN_TEST(test_tx_queue_enqueue_packet_with_transport_codes);
    RUN_TEST(test_tx_queue_trace_packet_enqueues_normally);
    RUN_TEST(test_tx_queue_all_packets_use_carrier_sense);
        RUN_TEST(test_radio_controller_initial_state_is_idle);
    RUN_TEST(test_radio_controller_transmits_immediately_when_cs_clear);
    RUN_TEST(test_radio_controller_completes_after_tx_done);
    RUN_TEST(test_radio_controller_schedules_retry_on_carrier_detected);
    RUN_TEST(test_radio_controller_retries_cs_after_delay);
    RUN_TEST(test_radio_controller_transmits_on_retry_success);
    RUN_TEST(test_radio_controller_transmits_after_max_retries);
    RUN_TEST(test_radio_controller_rejects_transmit_when_busy);
    RUN_TEST(test_radio_controller_handles_tx_timeout);
    RUN_TEST(test_radio_controller_rejects_oversized_data);
    RUN_TEST(test_radio_controller_uses_custom_cs_config);
    RUN_TEST(test_cs_config_defaults);
    RUN_TEST(test_radio_controller_does_not_affect_rx_during_idle);
    RUN_TEST(test_radio_controller_uses_source_pointer_directly);
    RUN_TEST(test_radio_controller_data_valid_through_retries);
    RUN_TEST(test_radio_controller_reports_pending_data_size);
    RUN_TEST(test_radio_controller_carrier_sense_disabled_by_default);
    RUN_TEST(test_radio_controller_enable_carrier_sense);
    RUN_TEST(test_radio_controller_carrier_sense_samples_noise_floor);
    RUN_TEST(test_radio_controller_carrier_sense_detects_signal_above_threshold);
    RUN_TEST(test_radio_controller_carrier_sense_ignores_noise);
    RUN_TEST(test_radio_controller_carrier_sense_schedules_retry_on_carrier);
    RUN_TEST(test_radio_controller_carrier_sense_transmits_when_clear);
    RUN_TEST(test_radio_controller_carrier_sense_disabled_transmits_immediately);
    RUN_TEST(test_radio_controller_carrier_sense_invalid_noise_floor_transmits);
    RUN_TEST(test_radio_controller_carrier_sense_retry_rechecks_rssi);
    RUN_TEST(test_radio_controller_configure_carrier_sense_for_bandwidth);
    RUN_TEST(test_radio_controller_narrow_bandwidth_uses_smaller_margin);
        RUN_TEST(test_power_save_initial_state_is_active);
    RUN_TEST(test_power_save_initial_last_repeat_is_zero);
    RUN_TEST(test_power_save_on_packet_repeated_updates_time);
    RUN_TEST(test_power_save_multiple_repeats_update_time);
    RUN_TEST(test_power_save_stays_active_before_timeout);
    RUN_TEST(test_power_save_enters_sleep_after_timeout);
    RUN_TEST(test_power_save_sleep_disables_rx);
    RUN_TEST(test_power_save_enters_sleep_with_no_repeats_from_start);
    RUN_TEST(test_power_save_wakes_after_sleep_duration);
    RUN_TEST(test_power_save_wake_enables_rx);
    RUN_TEST(test_power_save_stays_sleeping_before_duration);
    RUN_TEST(test_power_save_repeat_resets_timeout);
    RUN_TEST(test_power_save_wake_resets_last_repeat_time);
    RUN_TEST(test_power_save_full_cycle_sleep_wake_sleep);
    RUN_TEST(test_power_save_repeat_during_active_prevents_sleep);
    RUN_TEST(test_power_save_enabled_disabled);
    RUN_TEST(test_power_save_is_sleeping_helper);
    RUN_TEST(test_power_save_custom_config);
    RUN_TEST(test_power_save_config_defaults);
        RUN_TEST(test_packet_router_initial_state);
    RUN_TEST(test_packet_router_set_self_hash);
    RUN_TEST(test_packet_router_processes_advert_packet);
    RUN_TEST(test_packet_router_forwards_flood_packet);
    RUN_TEST(test_packet_router_does_not_forward_duplicate);
    RUN_TEST(test_packet_router_appends_self_hash_for_flood);
    RUN_TEST(test_packet_router_does_not_forward_when_disabled);
    RUN_TEST(test_packet_router_forwards_direct_when_next_hop);
    RUN_TEST(test_packet_router_drops_direct_when_not_next_hop);
    RUN_TEST(test_packet_router_does_not_forward_control_packets);
    RUN_TEST(test_packet_router_calculates_correct_priority);

    RUN_TEST(test_packet_router_duplicate_flood_never_forwarded_twice);
    RUN_TEST(test_packet_router_duplicate_control_request_never_triggers_twice);
    RUN_TEST(test_packet_router_duplicate_advert_still_processes_for_time_sync);
    RUN_TEST(test_packet_router_different_packets_both_forwarded);
    RUN_TEST(test_packet_router_control_response_marked_seen_but_not_processed);
    RUN_TEST(test_packet_router_null_event_handler_no_crash);
    RUN_TEST(test_packet_router_packet_exceeds_path_limit_not_forwarded);
    RUN_TEST(test_packet_router_repeater_disabled_no_forward);
    RUN_TEST(test_packet_router_malformed_discover_request_still_deduped);
    RUN_TEST(test_packet_router_flood_destined_for_self_not_forwarded);
    RUN_TEST(test_packet_router_stress_many_unique_packets);
    RUN_TEST(test_packet_router_stress_same_packet_many_times);
        RUN_TEST(test_noise_floor_estimator_initial_state_is_invalid);
    RUN_TEST(test_noise_floor_estimator_becomes_valid_after_min_samples);
    RUN_TEST(test_noise_floor_estimator_converges_to_stable_value);
    RUN_TEST(test_noise_floor_estimator_ewma_smooths_values);
    RUN_TEST(test_noise_floor_estimator_adapts_to_changing_environment);
    RUN_TEST(test_noise_floor_estimator_threshold_above_noise_floor);
    RUN_TEST(test_noise_floor_estimator_threshold_based_on_variance);
    RUN_TEST(test_noise_floor_estimator_minimum_margin_applied);
    RUN_TEST(test_noise_floor_estimator_detects_signal_above_threshold);
    RUN_TEST(test_noise_floor_estimator_ignores_signal_below_threshold);
    RUN_TEST(test_noise_floor_estimator_invalid_always_returns_false);
    RUN_TEST(test_noise_floor_estimator_respects_custom_min_samples);
    RUN_TEST(test_noise_floor_estimator_respects_custom_alpha);
    RUN_TEST(test_noise_floor_estimator_default_config);
    RUN_TEST(test_noise_floor_estimator_reset_clears_state);
    RUN_TEST(test_noise_floor_estimator_handles_extreme_rssi_values);
    RUN_TEST(test_noise_floor_estimator_sample_count_increments);
    RUN_TEST(test_margin_for_bandwidth_narrow_returns_small_margin);
    RUN_TEST(test_margin_for_bandwidth_medium_returns_default_margin);
    RUN_TEST(test_margin_for_bandwidth_wide_returns_larger_margin);
    RUN_TEST(test_noise_floor_config_for_bandwidth);
    RUN_TEST(test_noise_floor_estimator_with_bandwidth_config);

    RUN_TEST(test_path_hash_mode_default_is_max);
    RUN_TEST(test_path_hash_mode_get_returns_stored_value);
    RUN_TEST(test_path_hash_mode_set_accepts_0_1_2);
    RUN_TEST(test_path_hash_mode_set_rejects_3);
    RUN_TEST(test_path_hash_mode_set_rejects_larger_values);
    RUN_TEST(test_path_hash_mode_load_from_storage);
    RUN_TEST(test_path_hash_mode_load_constrains_invalid_stored_value);
    RUN_TEST(test_path_hash_mode_load_empty_storage_uses_default);
    RUN_TEST(test_path_hash_mode_save_persists_value);
    RUN_TEST(test_path_hash_mode_save_then_load_roundtrip);

    return UNITY_END();
}
